name: Build, Test & Publish

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - src/**
      - Dockerfile
  pull_request:
    branches:
      - develop # only when merging to develop
    paths:
      - .github/workflows/build.yml
      - src/**
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout source
        uses: actions/checkout@v2
      -
        name: Set variables
        id: variables
        env:
          GIT_TARGET_SHA: ${{ github.sha }}
        run: |
          echo "::set-output name=image_name::gcr.io/or-docker-images/${{ github.event.repository.name }}"
          echo "::set-output name=short_sha::$(echo ${GIT_TARGET_SHA:0:7})"
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Setup gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}
      -
        name: Docker auth
        run: gcloud auth configure-docker
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ steps.variables.outputs.image_name }}
          tags: |
            type=raw,enable=${{ github.ref == 'refs/heads/master' }},value=latest
            type=ref,event=pr
            type=raw,value=${{ steps.variables.outputs.short_sha }}
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          secrets: |
            composer-auth={"github-oauth": {"github.com": "${{ secrets.ORBITREMIT_BOT_PAT }}"}}
